#AdaptiveMobOptimizer config. Edit and run /amo reload.
#Thu Jun 11 14:55:40 ICT 2026
require_no_target=true
ignore_named=true
far_distance_blocks=128.0
base_tick_interval=4
adaptive_tps_scaling=true
max_tick_interval=20
newborn_grace_ticks=100
ignore_villagers=true
debug_log=false
enabled=true
target_tps=18.5
stats_window_ticks=1200
ignore_tamed=true
ignore_babies=true
require_no_navigation=true
boss_health_threshold=150.0
ignore_boss_like_mobs=true
hard_wake_distance_blocks=32.0
entity_blacklist=minecraft\:villager,minecraft\:wandering_trader,minecraft\:warden,minecraft\:wither
entity_whitelist=
min_distance_blocks=48.0
