#Scales overall attributes further
#Range: 1.0 ~ 100.0
globalMultiplier = 1.0
#Scales easy difficulty attributes
#Range: 1.5 ~ 25.0
easyMultiplier = 1.5
#Scales normal difficulty attributes
#Range: 2.0 ~ 50.0
normalMultiplier = 2.0
#Scales hard difficulty attributes
#Range: 3.0 ~ 100.0
hardMultiplier = 3.0

