
[compat]
	undergarden = true
	twilightforest = true
	toughasnails = true
	tconstruct = true
	quark = true
	mowziesmobs = true
	irons_spellbooks = true
	immersiveengineering = true
	iceandfire = true
	farmersdelight = true
	ecologics = true
	create = true
	cataclysm = true
	botania = true
	ars_nouveau = true
	alexscaves = true

