#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=curio;size=0", "id=charm;size=3", "id=belt;size=2"]

