
#Mob Configuration
[mob_configuration]
	#Enable the default ability of Icy Creeper Explosions to grief the environment. 
	#If you prefer their explosions to not damage the environment, disable this feature. [true / false]
	enablyIcyCreeperGriefing = true
	#Add mobs (preferably undead and aquatic) that the Drowned Necromancer can summon. 
	#To do so, enter the namespace ID of the mob, like "minecraft:drowned".
	#If this list is empty, drowned will be summoned instead.
	#If a mob chosen from this list cannot be spawned, a drowned will be summoned instead.
	drownedNecromancerMobSummons = ["minecraft:drowned", "dungeonsmobs:sunken_skeleton"]
	#Enable the Endersent's bossbar & fog to appear
	#Off by default, since it spoils stronghold locations. [true / false]
	enableEndersentBossBar = false
	#Add mobs (preferably undead) that the Necromancer can summon. 
	#To do so, enter the namespace ID of the mob, like "minecraft:zombie".
	#If this list is empty, zombies will be summoned instead.
	#If a mob chosen from this list cannot be spawned, a zombie will be summoned instead.
	necromancerMobSummons = ["minecraft:zombie", "minecraft:skeleton"]
	#Add mobs (preferably blaze-related) that the Wildfire can summon. 
	#To do so, enter the namespace ID of the mob, like "minecraft:blaze".
	#If this list is empty, blazes will be summoned instead.
	#If a mob chosen from this list cannot be spawned, a blaze will be summoned instead.
	wildfireMobSummons = ["minecraft:blaze"]
	#Add mobs that the Redstone Monstrosity can summon. 
	#To do so, enter the namespace ID of the mob, like "dungeonsmobs:redstone_cube".
	#If this list is empty, redstone cubes will be summoned instead.
	#If a mob chosen from this list cannot be spawned, a redstone cube will be summoned instead.
	redstoneMonstrosityMobSummons = ["dungeonsmobs:redstone_cube"]
	#Add mobs that the Mooshroom Monstrosity can summon. 
	#To do so, enter the namespace ID of the mob, like "minecraft:mooshroom".
	#If this list is empty, mooshrooms will be summoned instead.
	#If a mob chosen from this list cannot be spawned, a mooshroom will be summoned instead.
	mooshroomMonstrosityMobSummons = ["minecraft:mooshroom"]
	#Add mobs (preferably end-related) that the Endersent can summon. 
	#To do so, enter the namespace ID of the mob, like "dungeonsmobs:watchling".
	#If this list is empty, watchlings will be summoned instead.
	#If a mob chosen from this list cannot be spawned, a watchling will be summoned instead.
	endersentMobSummons = ["dungeonsmobs:watchling"]

	#Vanilla Mob Configuration
	[mob_configuration.vanilla_mob_configuration]
		#Enable the addition of additional attributes to Husks to make them as powerful as they are in Minecraft Dungeons. [true / false]
		enableStrongerHusks = true
		#Enables Spiders and Cave Spiders shooting webs as a ranged attack like they do in Minecraft Dungeons. [true / false]
		enableRangedSpiders = true
		#Makes Mooshrooms hostile, like in Minecraft Dungeons. [true / false]
		enableHostileMooshrooms = true

#Raid Configuration
[raid_configuration]
	#Enable the addition of Mountaineers to raids. [true / false]
	enableMountaineersInRaids = false
	#Enable the addition of Royal Guards to raids. [true / false]
	enableRoyalGuardsInRaids = false
	#Enable the addition of Geomancers to raids. [true / false]
	enableGeomancersInRaids = false
	#Enable the addition of Mages to raids. [true / false]
	enableMagesInRaids = false
	#Enable the addition of Windcallers to raids. [true / false]
	enableWindcallersInRaids = false
	#Enable the addition of Squall Golems to raids. [true / false]
	enableSquallGolemsInRaids = false
	#Enable the addition of Redstone Golems to raids. [true / false]
	enableRedstoneGolemsInRaids = false
	#Enable the addition of Iceologers to raids. [true / false]
	enableIceologersInRaids = false
	#Enable the addition of Armored Pillagers to raids. [true / false]
	enableArmoredPillagersInRaids = false
	#Enable the addition of Armored Vindicators to raids. [true / false]
	enableArmoredVindicatorsInRaids = false
	#Enable the addition of Redstone Monstrosities to raids. [true / false]
	enableRedstoneMonstrositiesInRaids = false

