#Heavier Weapons Configuration
#Thu Mar 26 11:11:26 ICT 2026
entityFreezeEnabled=true
cameraShakeIntensity=2.0
categoryDurations=dagger\:0,claw\:0,fist\:0,sickle\:0,soul_knife\:0,wand\:0,rapier\:1,sword\:2,cutlass\:2,katana\:2,coral_blade\:2,twin_blade\:2,spear\:2,trident\:2,staff\:2,pickaxe\:2,axe\:3,mace\:3,glaive\:3,scythe\:3,battlestaff\:3,lance\:3,claymore\:4,heavy_axe\:4,double_axe\:4,halberd\:4,hammer\:5,anchor\:5
hitstopDelayTicks=0
cameraShakeEnabled=true
hitstopEnabled=true
defaultHitstopTicks=2
critBonusTicks=2
