#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Aug 12 11:13:48 ICT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=Medium
enableShaders=true
